### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by ArthurCamara** [yahoo/FEL#8] opened 2017-05-08 02:00 UTC
I'm fairly new to the Java/Maven ecosystem, so, I'm sorry if this is completely unrelated to FEL itself.

After clonning the repository and running `mvn install`, running `java -Xmx10G com.yahoo.semsearch.fastlinking.FastEntityLinker --help` will always return the same error:
`Error: Could not find or load main class com.yahoo.semsearch.fastlinking.FastEntityLinker`
Tried running these both on a linux machine and on a Mac machine.

Is there any step that I'm missing? 
Thanks!

P.S.: In my Maven local repository, I can find both `/it/unimi/dsi/fastutil/` and `/com/yahoo/FEL/FEL/`

**Comment by aasish** [comment] 2017-05-13 20:50
Hi Arthur,

Can you copy & paste your ``mvn install`` output?

Thanks,
Aasish

**Comment by ArthurCamara** [comment] 2017-05-15 23:31
Hi Aasish, 
here is the output for `mvn install`

as a side note, I am able to run the code using mvn exec:java, like in:
`mvn exec:java -Dexec.mainClass=com.yahoo.semsearch.fastlinking.FastEntityLinker -Dexec.args="en/english-nov15.hash"`

```

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.yahoo.FEL:FEL:jar:0.1.0
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 83, column 11
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building FEL 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ FEL ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/hd0/Arthur/FEL/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ FEL ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 72 source files to /mnt/hd0/Arthur/FEL/target/classes
[WARNING] /mnt/hd0/Arthur/FEL/src/main/java/com/yahoo/semsearch/fastlinking/io/ExtractWikipediaAnchorText.java: Some input files use or override a deprecated API.
[WARNING] /mnt/hd0/Arthur/FEL/src/main/java/com/yahoo/semsearch/fastlinking/io/ExtractWikipediaAnchorText.java: Recompile with -Xlint:deprecation for details.
[WARNING] /mnt/hd0/Arthur/FEL/src/main/java/com/yahoo/semsearch/fastlinking/w2v/EmbeddingsServer.java: Some input files use unchecked or unsafe operations.
[WARNING] /mnt/hd0/Arthur/FEL/src/main/java/com/yahoo/semsearch/fastlinking/w2v/EmbeddingsServer.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ FEL ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/hd0/Arthur/FEL/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ FEL ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ FEL ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ FEL ---
[INFO] Building jar: /mnt/hd0/Arthur/FEL/target/FEL-0.1.0.jar
[INFO]
[INFO] --- maven-shade-plugin:2.1:shade (default) @ FEL ---
[INFO] Including xmlrpc-helma:xmlrpc-helma:jar:1.0 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.3 in the shaded jar.
[INFO] Including it.unimi.dsi:sux4j:jar:3.1.2 in the shaded jar.
[INFO] Including com.martiansoftware:jsap:jar:2.1 in the shaded jar.
[INFO] Including ch.qos.logback:logback-classic:jar:1.1.2 in the shaded jar.
[INFO] Including ch.qos.logback:logback-core:jar:1.1.2 in the shaded jar.
[INFO] Including org.slf4j:log4j-over-slf4j:jar:1.7.7 in the shaded jar.
[INFO] Including commons-configuration:commons-configuration:jar:1.8 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including commons-collections:commons-collections:jar:20040616 in the shaded jar.
[INFO] Including it.unimi.dsi:fastutil:jar:6.5.12 in the shaded jar.
[INFO] Including it.unimi.dsi:dsiutils:jar:2.1.9 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:16.0.1 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.6 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-client:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-common:jar:2.4.0 in the shaded jar.
[INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.5 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:2.5.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-auth:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.2.5 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.2.4 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:1.3.9 in the shaded jar.
[INFO] Including org.apache.zookeeper:zookeeper:jar:3.4.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-hdfs:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-client:jar:2.4.0 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-client:jar:1.9 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-server-common:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-api:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-common:jar:2.4.0 in the shaded jar.
[INFO] Including javax.xml.bind:jaxb-api:jar:2.2.2 in the shaded jar.
[INFO] Including javax.xml.stream:stax-api:jar:1.0-2 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1 in the shaded jar.
[INFO] Including javax.servlet:servlet-api:jar:2.5 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-core:jar:1.9 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.4.0 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-annotations:jar:2.4.0 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.2 in the shaded jar.
[INFO] Including xmlenc:xmlenc:jar:0.52 in the shaded jar.
[INFO] Including commons-httpclient:commons-httpclient:jar:3.1 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.4 in the shaded jar.
[INFO] Including commons-net:commons-net:jar:1.4.1 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty-util:jar:6.1.26 in the shaded jar.
[INFO] Including oro:oro:jar:2.0.8 in the shaded jar.
[INFO] Including jline:jline:jar:1.0 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-mapper-asl:jar:1.8.8 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-core-asl:jar:1.8.8 in the shaded jar.
[INFO] Including org.apache.avro:avro:jar:1.7.4 in the shaded jar.
[INFO] Including com.thoughtworks.paranamer:paranamer:jar:2.3 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.0.4.1 in the shaded jar.
[INFO] Including net.sf.trove4j:trove4j:jar:3.0.3 in the shaded jar.
[INFO] Including info.bliki.wiki:bliki-core:jar:3.0.19 in the shaded jar.
[INFO] Including org.apache.commons:commons-compress:jar:1.4.1 in the shaded jar.
[INFO] Including org.tukaani:xz:jar:1.0 in the shaded jar.
[INFO] Including edu.umd:cloud9:jar:1.5.0 in the shaded jar.
[WARNING] slf4j-log4j12-1.7.5.jar, logback-classic-1.1.2.jar define 3 overlappping classes:
[WARNING]   - org.slf4j.impl.StaticMarkerBinder
[WARNING]   - org.slf4j.impl.StaticLoggerBinder
[WARNING]   - org.slf4j.impl.StaticMDCBinder
[WARNING] hadoop-yarn-common-2.4.0.jar, hadoop-yarn-api-2.4.0.jar define 3 overlappping classes:
[WARNING]   - org.apache.hadoop.yarn.util.package-info
[WARNING]   - org.apache.hadoop.yarn.factories.package-info
[WARNING]   - org.apache.hadoop.yarn.factory.providers.package-info
[WARNING] log4j-over-slf4j-1.7.7.jar, log4j-1.2.17.jar define 29 overlappping classes:
[WARNING]   - org.apache.log4j.spi.OptionHandler
[WARNING]   - org.apache.log4j.spi.LoggerRepository
[WARNING]   - org.apache.log4j.NDC
[WARNING]   - org.apache.log4j.PatternLayout
[WARNING]   - org.apache.log4j.LogManager
[WARNING]   - org.apache.log4j.BasicConfigurator
[WARNING]   - org.apache.log4j.spi.ErrorHandler
[WARNING]   - org.apache.log4j.MDC
[WARNING]   - org.apache.log4j.AppenderSkeleton
[WARNING]   - org.apache.log4j.WriterAppender
[WARNING]   - 19 more...
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
[INFO] Attaching shaded artifact.
[INFO]
[INFO] --- maven-install-plugin:2.3:install (default-install) @ FEL ---
[INFO] Installing /mnt/hd0/Arthur/FEL/target/FEL-0.1.0.jar to /home/arthur/.m2/repository/com/yahoo/FEL/FEL/0.1.0/FEL-0.1.0.jar
[INFO] Installing /mnt/hd0/Arthur/FEL/pom.xml to /home/arthur/.m2/repository/com/yahoo/FEL/FEL/0.1.0/FEL-0.1.0.pom
[INFO] Installing /mnt/hd0/Arthur/FEL/target/FEL-0.1.0-fat.jar to /home/arthur/.m2/repository/com/yahoo/FEL/FEL/0.1.0/FEL-0.1.0-fat.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.109s
[INFO] Finished at: Mon May 15 20:19:38 BRT 2017
[INFO] Final Memory: 149M/612M
[INFO] ------------------------------------------------------------------------


```

**Comment by aasish** [comment] 2017-05-16 13:18
@ArthurCamara 
I am glad you got it working. I'd be happy to help you with any other issues. I am closing this one as the issue is resolved.

**Closed by aasish** 2017-05-16 13:18 UTC
